version: '3.7'

# Basic function options
x-victim: &victim
  labels:
    class: 'victim'
    cluster: 'pentest_lab'
x-monitoring: &monitoring
  labels:
    class: 'monitoring'
    cluster: 'pentest_lab'
x-red_team: &red_team
  labels:
    class: 'red_team'
    cluster: 'pentest_lab'
x-blue_team: &blue_team
  labels:
    class: 'blue_team'
    cluster: 'pentest_lab'
x-infra: &infra
  labels:
    class: 'infra'
    cluster: 'pentest_lab'
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: 'http://10.5.0.201:3100/loki/api/v1/push'

networks:
  pentest_lab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

services:
  # Default attack system.
  kali:
    <<: *red_team
    build:
      context: ./
      dockerfile: dockerfiles/kali
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.5
    hostname: kali
    volumes:
      - kali-data:/root/Documents

  # Nice to have infrastructure serices.
  heimdall:
    <<: *infra
    image: ghcr.io/linuxserver/heimdall
    environment:
      - PUID=nope_uid
      - PGID=nope_gid
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.225
    hostname: heimdall
    ports:
      - 7000:80
    volumes:
      - ./etc/heimdall/config:/config

  # Monitoring services.
  loki:
    <<: *monitoring
    image: grafana/loki
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.201
    hostname: loki
    volumes:
      - loki-data:/loki
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml
  prometheus:
    <<: *monitoring
    image: prom/prometheus
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.202
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    <<: *monitoring
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.203
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    <<: *monitoring
    image: grafana/grafana
    ports:
      - '8000:3000'
    networks:
      pentest_lab:
        ipv4_address: 10.5.0.200
    hostname: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
